config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/LandSlideHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/LandSlideHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-ultramarine-buffalo.sh
        container: qc.acc_snappy-ivory-butterfly
  QC.Doc:
    repos:
      github.com/edanya-uma/LandSlideHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-cinnamon-hippopotamus.sh
        container: qc.doc_queasy-aqua-badger
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-orange-caiman.sh
        container: qc.doc_wheezy-cobalt-zebra
      github.com/edanya-uma/LandSlideHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cyan-wasp.sh
        container: qc.doc_smelly-green-seal
  QC.Lic:
    repos:
      github.com/edanya-uma/LandSlideHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-gamboge-ostrich.sh
        container: qc.lic_gimpy-cyan-dog
  QC.Sty:
    repos:
      github.com/edanya-uma/LandSlideHySEA oclint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-beige-mammoth.sh
        container: qc.sty_cranky-maroon-bloodhound
  QC.Ver:
    repos:
      github.com/edanya-uma/LandSlideHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-ecru-rhinoceros.sh
        container: qc.ver_crappy-mustard-frog
timeout: 5400
