config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/LandSlideHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/LandSlideHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-grey-flounder.sh
        container: qc.acc_fuzzy-razzmatazz-sloth
  QC.Doc:
    repos:
      github.com/edanya-uma/LandSlideHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-aquamarine-foxhound.sh
        container: qc.doc_stinky-viridian-koala
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-xanthic-pinscher.sh
        container: qc.doc_seedy-alizarin-retriever
      github.com/edanya-uma/LandSlideHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cerise-camel.sh
        container: qc.doc_squeaky-flax-crab
  QC.Lic:
    repos:
      github.com/edanya-uma/LandSlideHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-goldenrod-newt.sh
        container: qc.lic_nippy-chartreuse-buffalo
  QC.Sty:
    repos:
      github.com/edanya-uma/LandSlideHySEA oclint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-turquoise-capuchin.sh
        container: qc.sty_nippy-cyan-crocodile
  QC.Ver:
    repos:
      github.com/edanya-uma/LandSlideHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-turquoise-gecko.sh
        container: qc.ver_geeky-zucchini-moorhen
timeout: 5400
