config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/LandSlideHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/LandSlideHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-brass-tarsier.sh
        container: qc.acc_leaky-blue-fox
  QC.Doc:
    repos:
      github.com/edanya-uma/LandSlideHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-pumpkin-koala.sh
        container: qc.doc_bumpy-magenta-affenpinscher
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-purple-albatross.sh
        container: qc.doc_ugly-goldenrod-raccoon
      github.com/edanya-uma/LandSlideHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-maroon-spitz.sh
        container: qc.doc_greasy-cardinal-deer
  QC.Lic:
    repos:
      github.com/edanya-uma/LandSlideHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-viridian-chameleon.sh
        container: qc.lic_sloppy-malachite-hedgehog
  QC.Sty:
    repos:
      github.com/edanya-uma/LandSlideHySEA oclint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-alizarin-caterpillar.sh
        container: qc.sty_flimsy-taupe-dragonfly
  QC.Ver:
    repos:
      github.com/edanya-uma/LandSlideHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-green-mandrill.sh
        container: qc.ver_stinky-lime-leopard
timeout: 5400
