config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/LandSlideHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/LandSlideHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-zucchini-hummingbird.sh
        container: qc.acc_woozy-razzmatazz-blue
  QC.Doc:
    repos:
      github.com/edanya-uma/LandSlideHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-goldenrod-cat.sh
        container: qc.doc_gamy-violet-spoonbill
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-smalt-owl.sh
        container: qc.doc_flaky-cornflower-spoonbill
      github.com/edanya-uma/LandSlideHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-razzmatazz-lion.sh
        container: qc.doc_flaky-chocolate-bongo
  QC.Lic:
    repos:
      github.com/edanya-uma/LandSlideHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-amber-quoll.sh
        container: qc.lic_ready-ultramarine-chameleon
  QC.Sty:
    repos:
      github.com/edanya-uma/LandSlideHySEA oclint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-cerise-grouse.sh
        container: qc.sty_pokey-tangerine-echidna
  QC.Ver:
    repos:
      github.com/edanya-uma/LandSlideHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-bistre-tiger.sh
        container: qc.ver_surly-goldenrod-ocelot
timeout: 5400
