config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/LandSlideHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/LandSlideHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-thistle-sheepdog.sh
        container: qc.acc_sickly-brass-okapi
  QC.Doc:
    repos:
      github.com/edanya-uma/LandSlideHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-copper-ferret.sh
        container: qc.doc_baggy-buff-kudu
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-sapphire-cougar.sh
        container: qc.doc_lousy-charcoal-mongoose
      github.com/edanya-uma/LandSlideHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-fuchsia-mongoose.sh
        container: qc.doc_scummy-amaranth-boar
  QC.Lic:
    repos:
      github.com/edanya-uma/LandSlideHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cornflower-zonkey.sh
        container: qc.lic_skimpy-pumpkin-cat
  QC.Sty:
    repos:
      github.com/edanya-uma/LandSlideHySEA oclint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-sangria-akbash.sh
        container: qc.sty_snippy-flax-boar
  QC.Ver:
    repos:
      github.com/edanya-uma/LandSlideHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-pink-pig.sh
        container: qc.ver_bumpy-wisteria-pinscher
timeout: 5400
