config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/LandSlideHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/LandSlideHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-asparagus-scorpion.sh
        container: qc.acc_bluesy-cobalt-mammoth
  QC.Doc:
    repos:
      github.com/edanya-uma/LandSlideHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-mustard-centipede.sh
        container: qc.doc_skanky-thistle-woodlouse
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-periwinkle-mongoose.sh
        container: qc.doc_silly-platinum-ocelot
      github.com/edanya-uma/LandSlideHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-denim-pinscher.sh
        container: qc.doc_geeky-seashell-bobcat
  QC.Lic:
    repos:
      github.com/edanya-uma/LandSlideHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-lavender-grouse.sh
        container: qc.lic_queasy-ecru-hippopotamus
  QC.Sty:
    repos:
      github.com/edanya-uma/LandSlideHySEA oclint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-chestnut-bobcat.sh
        container: qc.sty_fuzzy-heliotrope-ocelot
  QC.Ver:
    repos:
      github.com/edanya-uma/LandSlideHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-magenta-tapir.sh
        container: qc.ver_gummy-salmon-bombay
timeout: 5400
