config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/LandSlideHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/LandSlideHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-ruby-macaque.sh
        container: qc.acc_crappy-myrtle-wasp
  QC.Doc:
    repos:
      github.com/edanya-uma/LandSlideHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-amethyst-anteater.sh
        container: qc.doc_cranky-white-uguisu
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-pear-chin.sh
        container: qc.doc_droopy-cerulean-rat
      github.com/edanya-uma/LandSlideHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-viridian-shrew.sh
        container: qc.doc_scanty-flax-capybara
  QC.Lic:
    repos:
      github.com/edanya-uma/LandSlideHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-coral-burmese.sh
        container: qc.lic_freaky-khaki-akbash
  QC.Sty:
    repos:
      github.com/edanya-uma/LandSlideHySEA oclint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-chartreuse-giraffe.sh
        container: qc.sty_gimpy-blue-vole
  QC.Ver:
    repos:
      github.com/edanya-uma/LandSlideHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-emerald-gopher.sh
        container: qc.ver_snazzy-amber-tang
timeout: 5400
