config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/LandSlideHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/LandSlideHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-azure-anteater.sh
        container: qc.acc_silly-coral-forest
  QC.Doc:
    repos:
      github.com/edanya-uma/LandSlideHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-zucchini-fossa.sh
        container: qc.doc_stuffy-olivine-newfoundland
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chartreuse-uakari.sh
        container: qc.doc_gummy-ruby-yak
      github.com/edanya-uma/LandSlideHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cobalt-dalmatian.sh
        container: qc.doc_crappy-aqua-wolf
  QC.Lic:
    repos:
      github.com/edanya-uma/LandSlideHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-plum-beagle.sh
        container: qc.lic_lumpy-tangerine-moose
  QC.Sty:
    repos:
      github.com/edanya-uma/LandSlideHySEA oclint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-amber-frigatebird.sh
        container: qc.sty_shaky-malachite-ocelot
  QC.Ver:
    repos:
      github.com/edanya-uma/LandSlideHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-beige-seal.sh
        container: qc.ver_squirrely-vermilion-greyhound
timeout: 5400
