config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/LandSlideHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/LandSlideHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-turquoise-sloth.sh
        container: qc.acc_baggy-cerulean-kudu
  QC.Doc:
    repos:
      github.com/edanya-uma/LandSlideHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-ivory-dolphin.sh
        container: qc.doc_breezy-lilac-turkey
      github.com/edanya-uma/LandSlideHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-chestnut-dodo.sh
        container: qc.doc_sloppy-razzmatazz-orangutan
      github.com/edanya-uma/LandSlideHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-auburn-bombay.sh
        container: qc.doc_foggy-viridian-tamarin
  QC.Lic:
    repos:
      github.com/edanya-uma/LandSlideHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-periwinkle-eleuth.sh
        container: qc.lic_flabby-silver-buzzard
  QC.Sty:
    repos:
      github.com/edanya-uma/LandSlideHySEA oclint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-amethyst-lemur.sh
        container: qc.sty_cloudy-chartreuse-antelope
  QC.Ver:
    repos:
      github.com/edanya-uma/LandSlideHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-pink-grasshopper.sh
        container: qc.ver_dorky-lemon-blue
timeout: 5400
